POST http://localhost:2002/api/child
Content-Type: application/json

# {
#   "name": "Patience Bento"
# }

# {
#   "name": "Erica Zeal",
#   "thresholds": [
#     { "threshold": "Ate it" }, 
#     { "threshold": "touched it" }]
# }

{
  "name": "Den Bavidson",
  "thresholds": [
    { "threshold": "didn't throw it" },
    { "threshold": "tasted" }
  ]
}

# {
#   "name": "Cara Brug",
#   "thresholds": [
#     { "thresholdId": "652a1dff98921751b5cf3c0e" }, 
#     { "threshold": "danced on" }
#   ]
# }