POST http://localhost:2002/api/child
Content-Type: application/json

# {
#   "name": "Patience Bento"
# }

# {
#   "name": "Erica Zeal",
#   "tries": [
#     { "try": "Ate it" }, 
#     { "try": "touched it" }]
# }

{
  "name": "Den Bavidson",
  "tries": [
    { "try": "didn't throw it" },
    { "try": "tasted" }
  ]
}

# {
#   "name": "Cara Brug",
#   "tries": [
#     { "tryId": "652a1dff98921751b5cf3c0e" }, 
#     { "try": "danced on" }
#   ]
# }