# DELETE http://localhost:2002/api/try/hints

DELETE http://localhost:2002/api/kid/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkV4YW1wbGUiLCJpZCI6IjY1YjE4OGY4ZTNkYzAxNDI2ZDQ5MzQ3NSIsImlhdCI6MTcwNjI5MjkwM30.DD5MoegQqcb79DKloxIQh-uYCJdsLmlcN0Yu0rlxyXM

# DELETE http://localhost:2002/api/kid

